### PR TITLE
New release scripts

### PR DESCRIPTION
**Pull request by stuartc**
New flow

```
./bin/cli check-package-json -f <path>
./bin/cli release <path>
./bin/cli package-release -u <path>
```

### CODE REVIEW

**Comment by stuartc** [comment]
Feedback from call with @lakhassane:

- We repeatedly got an error about a tag already existing - something was creating the tag (_before?_) `npm version ...` was being run.
- The `upload-release` script was looking for a file path prefixed with `@openfn/...` which doesn't exist.

**Comment by stuartc** [comment]
btw, I'm using `npm 7.6.3`

**Comment by taylordowns2000** [comment]
OK, in the end did you guys use the script or go back to the old style of releasing?

**Comment by taylordowns2000** [comment]
1. proposed changes to package.json not working on mac
2. upload release goes to the wrong path? (`@openfn/thing` issue)
3. build.tgz generated on mac is empty
4. ast.json generation is broken

## 1. proposed changes not working on mac
on `macos`, it constantly thinks there are changes required when none are required
image

on `ubuntu`, this isn't an issue.

## 2. upload-release with wrong filepath
image

## 3. ast that's built by new style isn't read by platform-app?

- td gathering more data
- @lakhassane says that the `build.tgz` is actually completely empty. more info to come.

## 4. ast.json generation is broken
The `ast` generated after build remains empty. So no documentation is available.
Screen Shot 2021-05-14 at 16 39 40

## 5. unable to release on ubuntu, more stuff for monday

```
❯ ./bin/cli release ./adaptors/adaptor
  ✔ Pre-flight checks
? The following new files are not already part of your published package:
- docs/module-Adaptor.html
Continue? Yes

Publish a new version of @openfn/language-template (current: 1.1.4)

Commits:
- newline stuff  2d1639e
- update docs  d5818da
- generate documentation  4499596

Commit Range:
v1.1.4...main

Registry:
https://registry.npmjs.org/

? Select semver increment or specify new version patch  1.1.5
  ✔ Prerequisite check
  ✔ Git
  ✔ Installing dependencies using npm
  ✔ Prerequisite check
  ✔ Git
  ✔ Installing dependencies using npm
  ✔ Running tests using npm
  ✔ Bumping version using npm
  ✖ Publishing package using npm
    → The project was rolled back to its previous state.
    Pushing tags
    Creating release draft on GitHub
Error publishing package:
Command failed with exit code 1: npm publish --access public
npm WARN exec The following package was not found and will be installed: @openfn/simple-ast
npm notice 
npm notice 📦  @openfn/language-template@1.1.5
npm notice === Tarball Contents === 
npm notice 35.1kB LICENSE       
npm notice 7.7kB  LICENSE.LESSER
npm notice 947B   README.md     
npm notice 12.1kB ast.json      
npm notice 4.2kB  lib/Adaptor.js
npm notice 1.2kB  lib/index.js  
npm notice 1.2kB  lib/utils.js  
npm notice 1.2kB  package.json  
npm notice === Bundled Dependencies === 
npm notice jsonpath-plus
npm notice @openfn/language-common
npm notice axios
npm notice follow-redirects
npm notice lodash
npm notice === Tarball Details === 
npm notice name:          @openfn/language-template               
npm notice version:       1.1.5                                   
npm notice filename:      @openfn/language-template-1.1.5.tgz     
npm notice package size:  524.8 kB                                
npm notice unpacked size: 2.2 MB                                  
npm notice shasum:        b61f1ee2f6971afb133e9208765c052fd827da53
npm notice integrity:     sha512-nPScRy/7yBc0X[...]l4ifISYdEwWFg==
npm notice bundled deps:  5                                       
npm notice bundled files: 0                                       
npm notice own files:     1135                                    
npm notice total files:   1135                                    
npm notice 
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/@openfn%2flanguage-template - You cannot publish over the previously published versions: 1.1.5.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/taylor/.npm/_logs/2021-05-14T17_05_49_030Z-debug.log

> @openfn/language-template@1.1.5 prepack
> npx @openfn/simple-ast --adaptor ./lib/Adaptor.js --output ast.json

Parsing ./lib/Adaptor.js
├─ create is properly documented ✓
└─ createPatient is properly documented ✓
Gathering documentation for language-common
Documented the following exports from language-common: [
  "alterState",
  "sourceValue",
  "dataPath",
  "dataValue",
  "lastReferenceValue",
  "each",
  "field",
  "fields",
  "merge"
]
The AST has been written.

The project was rolled back to its previous state.
❯ ./bin/cli package-release -u ./adaptors/adaptor
  ✔ npm pack
  ✔ rearrange tarball for Github
  ⠼ Upload build to Github
Deprecation: [@octokit/request-error] `error.code` is deprecated, use `error.status`.
  ✔ Stat build tarball
  ✔ Check for Github token
  ✖ Check for existing release
    → v1.1.4 does not exist for repo: adaptor
    Uploading release
  ✔ npm pack
  ✔ rearrange tarball for Github
  ✖ Upload build to Github
    → v1.1.4 does not exist for repo: adaptor
cli package-release [path]

packages a tarball with all production dependencies baked in

Positionals:
  path  the local git repo of the adaptor                [string] [default: "."]

Options:
      --version  Show version number                                   [boolean]
  -u, --upload   upload the resulting tarball to github, requires GH_TOKEN
                                                      [boolean] [default: false]
  -d, --debug                                         [boolean] [default: false]
      --help     Show help                                             [boolean]

Error: v1.1.4 does not exist for repo: adaptor
    at /home/taylor/devtools/lib/tasks/index.js:115:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  context: [Object: null prototype] {}
}
❯ ./bin/cli release ./adaptors/adaptor
  ✔ Pre-flight checks
? The following new files are not already part of your published package:
- docs/module-Adaptor.html
Continue? (y/N) 
```

**Comment by stuartc** [comment]
@taylordowns2000 out of time for today but we're like pretty much done...

I used the git commit way of getting release notes in - but it seems that Github doesn't format them :(

image

So we will need to change that strategy and make a specific payload when creating the release.

Also I found out the reason I was having a _lot_ of issues (like over weeks) with `npm` which you may or may not have experienced... I highly recommend any and all of us update our `asdf` and the `nodejs` plugin for it...

**Review by taylordowns2000 — APPROVED** [review]

**Pull request merged**
